import json
import os
import ollama
from config import MODELS, LLM_PROMPT_TEMPLATE, RAW_DATA_PATH, RESULTS_DIR
from data_profiler import get_dataset_metadata

def run_llm_copilot():
    """
    Connects to Ollama and asks models to analyze metadata.
    Saves outputs to the results directory.
    """
    os.makedirs(RESULTS_DIR, exist_ok=True)
    
    print(f"Extracting metadata from {RAW_DATA_PATH}...")
    metadata = get_dataset_metadata(RAW_DATA_PATH)
    metadata_json = json.dumps(metadata, indent=2)
    
    prompt = LLM_PROMPT_TEMPLATE.format(metadata=metadata_json)
    
    for model_name in MODELS:
        print(f"Running prompt on model: {model_name}...")
        messages = [
            {
                'role': 'user',
                'content': prompt
            }
        ]
        
        max_retries = 3
        for attempt in range(max_retries):
            try:
                response = ollama.chat(model=model_name, messages=messages, format='json')
                output = response['message']['content']
                
                # Try to parse to ensure it's valid before saving
                import re
                match = re.search(r'\{[\s\S]*\}', output)
                content_to_parse = match.group(0) if match else output
                json.loads(content_to_parse) # This will throw JSONDecodeError if invalid
                
                # Save the raw JSON output
                safe_model_name = model_name.replace(":", "_")
                out_file = os.path.join(RESULTS_DIR, f"{safe_model_name}_suggestions.json")
                
                with open(out_file, 'w', encoding='utf-8') as f:
                    f.write(output)
                print(f"Saved suggestions for {model_name} to {out_file}")
                break # Success, break out of retry loop
                
            except json.JSONDecodeError:
                print(f"Attempt {attempt+1} failed: Invalid JSON generated by {model_name}. Retrying...")
                if attempt == max_retries - 1:
                    print(f"Max retries reached for {model_name}. Skipping.")
                else:
                    messages.append({'role': 'assistant', 'content': output})
                    messages.append({
                        'role': 'user', 
                        'content': 'Your previous output was invalid JSON. Please fix the syntax errors and output strictly valid JSON.'
                    })
            except Exception as e:
                print(f"Failed to run model {model_name}. Error: {e}")
                break

if __name__ == "__main__":
    run_llm_copilot()
